### PR TITLE
fix: resolve promise on ios every time

### LINKED ISSUE #865: Promise "open" is never resolved when canceling printing
### Steps to reproduce
1. Open a image in Base64, like this:
```js
                 const openResult = await Share.open({
                        failOnCancel: true,
                        title: 'Some title',
                        url: 'data:image/jpg;base64,foobarbazz',
                        filename: 'file-name.jpg',
                    });
```

2. Select "Print" option.

image

3. Then click on "Cancel" option.

image

### Expected behaviour

The promise should be rejected (failOnCancel=true) or resolved (failOnCancel=false).

### Actual behaviour

The promise never end.

### Environment

- **React Native version**: 0.61.5
- **React Native platform + platform version**: iOS 13.7

### react-native-share

**Version**: 3.8.0

### Link to repo (highly encouraged)

I don't think it's necessary.

### PR DESCRIPTION
**Pull request by krystofcelba**
# Overview
The `Share.open` promise doesn't resolve in some situations on iOS. For example when you cancel printing. It's well described in #865. This PR fixes that.

Fix #865 #857

# Test Plan

Please check #865, there are steps for reproduce and it should work as expected with this fix.

### CODE REVIEW

File: ios/RNShare.m [hunk 1]
```diff
@@ -266,7 +266,7 @@ - (NSDictionary *)constantsToExport
         if (activityError) {
             [controller  dismissViewControllerAnimated:true completion:nil];
             failureCallback(activityError);
-        } else if (completed || activityType == nil) {
```
Comment (krystofcelba) [inline ios/RNShare.m:269]: The condition here is unnecessary as the completion is checked [https://github.com/krystofcelba/react-native-share/blob/80fc9967efb4162e19950eb0f209bc2e14a49231/index.js#L268](here) in JS code and in situations like canceled print it causes that the JS callback isn't called at all.

**Review by MateusAndrade — APPROVED** [review]
Nice!!! Thanks, @krystofcelba! 🚀 🚀 🚀

**Comment by cristianoccazinsp** [comment]
This introduced the following bug: https://github.com/react-native-share/react-native-share/issues/972

I'm already testing a "fix", but it would be great to get @krystofcelba input.

**Comment by cristianoccazinsp** [comment]
Proposed update: 

```
__weak UIActivityViewController* weakShareController = shareController;
    shareController.completionWithItemsHandler = ^(NSString *activityType, BOOL completed, __unused NSArray *returnedItems, NSError *activityError) {
        
        // always dismiss since this may be called from cancelled shares
        // but the share menu would remain open, and our callback would fire again on close
        [controller dismissViewControllerAnimated:true completion:nil];
        
        if (activityError) {
            failureCallback(activityError);
        } else {
            successCallback(@[@(completed), RCTNullIfNil(activityType)]);
        }
        
        // clear the completion handler to prevent cycles
        if(weakShareController){
            weakShareController.completionWithItemsHandler = nil;
        }
    };
```

This has the side effect that the share UI is always closed if the selected app was "cancelled".  However, it doesn't seem possible to detect if the share UI was closed automatically by the system or not
